{% set name = "medenv" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/medenv-{{ version }}.tar.gz
  sha256: ac5f29f4bd80be00625ece87eea02ac0a8f6208406df3ff51419ebf883e485c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - netcdf4 >=1.5.8
    - tqdm >=4.66.1
    - pandas >=2.1.3
    - xarray >=2023.11.0
    - lxml >=4.9.3
    - copernicusmarine >=2.0.1

test:
  - python:
      imports:
        - medenv
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true

about:
  homepage: https://github.com/jeremyfix/medenv
  repository: https://github.com/jeremyfix/medenv
  summary: "Python package to get environmental data from CMEMS, etopo, woa."
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeremyfix
